/**********************************************************************
 * I'm not including this in common because I generated this, and I'd like to experiment
 * with Blend4Web's existing externs first.
 *
 * Extern for b4w
 * Generated by http://jmmk.github.io/javascript-externs-generator
 * Got it from plugging in the file
 * https://raw.githubusercontent.com/TriumphLLC/Blend4Web/master/tools/closure-compiler/extern_modules.js
 **********************************************************************/
var b4w = {
  "module": {},
  "cleanup": function () {},
  "register": function () {},
  "require": function () {},
  "module_check": function () {},
  "get_namespace": function () {},
  "worker_listeners": {},
  "worker_namespaces": {}
};
/**********************************************************************
 * End Generated Extern for b4w
/**********************************************************************/
